### ISSUE TITLE
Ingress UKB fMRI Data in xcp-d

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/informatics_misc#52]
UKB minimally preprocessed fMRI data has the following steps done:

>The processed rfMRI data is in folder rfMRI.ica. The following pre-processing was applied: motion correction using MCFLIRT [Jenkinson et al., 2002]; grand-mean intensity normalisation of the entire 4D dataset by a single multiplicative fac- tor; highpass temporal filtering (Gaussian-weighted least-squares straight line fitting, with sigma=50.0s); EPI unwarping (utilising the fieldmaps as described above); GDC unwarping. Finally, structured artefacts are removed by ICA+FIX processing (Indepen- dent Component Analysis followed by FMRIB’s ICA-based X-noiseifier [Beckmann and Smith, 2004, Salimi-Khorshidi et al., 2014, Griffanti et al., 2014]). FIX was hand-trained on 40 Biobank rfMRI datasets, and leave-one-out testing showed (mean/median) 99.1/100.0% classification accuracy for non-artefact components and 98.1/98.3% accuracy for artefact components. The final pre-processed rfMRI timeseries data is filtered_func_data_clean. At this point no lowpass temporal or spatial filtering has been applied.

The high-pass filter corresponds to ~0.01 Hz.

Felix may have fMRIPrepped UKB data, but it may not be shareable. Ted will talk to Hanke about sharing.

If the fMRIPrepped data are not shareable (or don't cover the sample we need), then we'll have to figure out how to work with the FIXed and filtered data. All of the other datasets have GSR done, so we may want to use the FIX-denoised data and apply GSR on top of that.

**Comment by mattcieslak** [comment]
Investigate how possible it would be to use transforms/warps to get native data into minimally preprocessed form

**Comment by mattcieslak** [comment]
Ted to follow up with Guray

**Comment by tsalo** [comment]
From our nicharts meetings, I think we came to the conclusion that we should write a small script/tool to run the parcellation, without actually running UKB data through XCP-D, since the UKB data have already been denoised.

**Comment by tsalo** [comment]
Going to close this based on the above.
